### ISSUE TITLE
NullpointerException in the SaverLoader of Project

### ISSUE THREAD

**Issue by NeilCorH** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#17]
How you can recreate the Bug:
Load the project-file "PreferenceBug" into the program.
Try to open another project-file. Press safe changes.
Now the NullpointerException is thrown.
Bug found on 1.4.05

**Comment by Skypr** [comment]
I traced the error a bit in the debugger, and it seems to be caused, because the input type wasn't set (i don't know from where it is supposed to be set), nikolai, do you maybe know where that can coe from (probably somewhere in the saverloader, or what do you think?)

**Comment by NikolaiLMS** [comment]
Cause was inconsistent naming of `ElectionTypeContainer.id` for the preference voting input type.
Was named "list_of_candidate_placements_per_voter" in `ElectionTemplateHandler:48` and `CBMCCodeGenerator:291`, and "list_of_candidates_per_voter" everywhere else.
Fixed by enforcing "list_of_candidates_per_voter" naming in [commit 6c55f199](https://github.com/NikolaiLMS/PSE-Wahlverfahren-Implementierung/commit/6c55f199df706bad8327f7f6f37f5fb1a3fe10e1).
Closing issue.
New issue concerning potential refactoring of `inputIds` and `resultIds` in `ElectionTemplateHandler` [has been opened](https://github.com/NikolaiLMS/PSE-Wahlverfahren-Implementierung/issues/20).
