### ISSUE TITLE
Swap out Magic Strings in the ElectionTemplateHandler for Enums.

### ISSUE THREAD

**Issue by NeilCorH** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#20]
The stringsarrays inputIds and resultIds should be enums because they are used in other classes.
Because I don't know where else in the project these "magic strings" are used I want to open this Issue to discuss this.

**Comment by bigolol** [comment]
im on it

**Comment by bigolol** [comment]
So...I've basically done the refactoring. However, in order to decouple the id strings in the stringfiles from the enums, i also had to add another class called EnumToIdMapping. If you give it the string rep of an enum, it returns the id this enum used to represent in the stringfile. This way, we can in future arbitrarily change the enum names without having to worry about the name of the ids in the file. This also enables us to not have to change the already saved election files since they still use the old ids.

**Comment by NeilCorH** [comment]
Sounds good. Can you push it to main?

**Comment by bigolol** [comment]
i have
